---
name: DB Solr Sync on Schedule

on:   # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 4 * * *'  # every day at 4am UTC

jobs:
  db-solr-sync:
    name: DB Solr Sync On Schedule
    strategy:
      matrix:
        environ: [development, staging, prod]
        include:
          - environ: development
            ram: 1G
          - environ: staging
            ram: 3G
          - environ: prod
            ram: 3G
    runs-on: ubuntu-latest
    environment: ${{matrix.environ}}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run task
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            cf run-task catalog-admin
            --command "ckan geodatagov db-solr-sync"
            --name 'db-solr-sync scheduled (CI)'
            -m ${{ matrix.ram }} -k 1500M
          cf_org: gsa-datagov
          cf_space: ${{ matrix.environ }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: monitor task output
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            tools/monitor_cf_logs.sh catalog-admin
            'db-solr-sync scheduled (CI)' 'geodatagov'
          cf_org: gsa-datagov
          cf_space: ${{ matrix.environ }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
