---
name: Tracking Update

on:   # yamllint disable-line rule:truthy
  schedule:
    - cron: '30 7 * * *'  # every day at 7:30am UTC

jobs:
  tracking-update:
    name: geodatagov tracking update
    strategy:
      max-parallel: 1
      matrix:
        environ: [development, staging, prod]
        include:
          - environ: development
            ram: 1G
          - environ: staging
            ram: 2G
          - environ: prod
            ram: 2G
    runs-on: ubuntu-latest
    environment: ${{matrix.environ}}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run task
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            cf run-task catalog-admin
            --command "ckan geodatagov tracking-update"
            --name 'tracking update scheduled (CI)'
            -m ${{ matrix.ram }} -k 2G
          cf_org: gsa-datagov
          cf_space: ${{ matrix.environ }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: monitor task output
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            tools/monitor_cf_logs.sh catalog-admin
            'tracking update scheduled (CI)' 'geodatagov'
          cf_org: gsa-datagov
          cf_space: ${{ matrix.environ }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
